steps:
  # Build a temporary container with alembic
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/loyalty-migration:latest', 
           '--build-arg', 'DB_USER=${_DB_USER}',
           '--build-arg', 'DB_PASS=${_DB_PASS}',
           '--build-arg', 'DB_NAME=${_DB_NAME}',
           '--build-arg', 'CLOUD_SQL_CONNECTION_NAME=${_CLOUD_SQL_CONNECTION_NAME}',
           '-f', 'Dockerfile.migrate', '.']
  
  # Run the migration in Cloud SQL
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', 'gcr.io/$PROJECT_ID/loyalty-migration:latest']

substitutions:
  _DB_USER: postgres
  _DB_PASS: changeme
  _DB_NAME: loyalty
  _CLOUD_SQL_CONNECTION_NAME: ${PROJECT_ID}:us-central1:loyalty-db

options:
  logging: CLOUD_LOGGING_ONLY 