"""add loyalty, submissions, claimed_rewards, audit_logs

Revision ID: 2e38b4c5d7c0
Revises: bb8c1ff5c2eb
Create Date: 2025-04-18 22:21:10.144947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e38b4c5d7c0'
down_revision = 'bb8c1ff5c2eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('claimed_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('reward_name', sa.String(), nullable=True),
    sa.Column('threshold_id', sa.Integer(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claimed_rewards_id'), 'claimed_rewards', ['id'], unique=False)
    op.create_index(op.f('ix_claimed_rewards_restaurant_id'), 'claimed_rewards', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_claimed_rewards_uid'), 'claimed_rewards', ['uid'], unique=False)
    op.create_table('loyalty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('restaurant_points', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('punches', sa.Integer(), nullable=True),
    sa.Column('redemption_history', sa.JSON(), nullable=True),
    sa.Column('visited_restaurants', sa.JSON(), nullable=True),
    sa.Column('last_spin_time', sa.DateTime(), nullable=True),
    sa.Column('spin_history', sa.JSON(), nullable=True),
    sa.Column('referral_codes', sa.JSON(), nullable=True),
    sa.Column('referrals_made', sa.JSON(), nullable=True),
    sa.Column('referred_by', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loyalty_id'), 'loyalty', ['id'], unique=False)
    op.create_index(op.f('ix_loyalty_restaurant_id'), 'loyalty', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_loyalty_uid'), 'loyalty', ['uid'], unique=False)
    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('amount_spent', sa.Float(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.restaurant_id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_submissions_restaurant_id'), 'submissions', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=False)
    op.create_index(op.f('ix_submissions_uid'), 'submissions', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_uid'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_restaurant_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_loyalty_uid'), table_name='loyalty')
    op.drop_index(op.f('ix_loyalty_restaurant_id'), table_name='loyalty')
    op.drop_index(op.f('ix_loyalty_id'), table_name='loyalty')
    op.drop_table('loyalty')
    op.drop_index(op.f('ix_claimed_rewards_uid'), table_name='claimed_rewards')
    op.drop_index(op.f('ix_claimed_rewards_restaurant_id'), table_name='claimed_rewards')
    op.drop_index(op.f('ix_claimed_rewards_id'), table_name='claimed_rewards')
    op.drop_table('claimed_rewards')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
