"""add updated_at to orders table

Revision ID: 3446abc02b28
Revises: 4f067dc2f3f8
Create Date: 2025-04-29 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3446abc02b28'
down_revision = '4f067dc2f3f8' # Ensure this points to the latest head before this change
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.now(), onupdate=sa.func.now()))
    # Manually set existing rows to have created_at as updated_at, or now()
    # For SQLite, direct update after add_column is simpler.
    # For other DBs, server_default might only apply to new rows.
    # Setting server_default and onupdate in add_column is good.
    # We can also issue an update statement for existing NULLs if necessary.
    op.execute('UPDATE orders SET updated_at = created_at WHERE updated_at IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###
