"""create_inventory_tables

Revision ID: 475a248d9153
Revises: be482d49863e
Create Date: 2025-05-16 15:04:26.502936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475a248d9153'
down_revision = 'be482d49863e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('restaurant_id', sa.String(), sa.ForeignKey('restaurants.restaurant_id'), nullable=False, index=True),
        sa.Column('menu_item_id', sa.Integer(), sa.ForeignKey('menu_items.id'), nullable=False, index=True),
        sa.Column('quantity', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('unit', sa.String(length=50), nullable=False),
        sa.Column('low_stock_threshold', sa.Float(), nullable=True),
        sa.Column('last_updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint('restaurant_id', 'menu_item_id', name='_restaurant_menu_item_uc')
    )

    op.create_table('inventory_update_logs',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('inventory_item_id', sa.Integer(), sa.ForeignKey('inventory_items.id'), nullable=False, index=True),
        sa.Column('changed_by_user_id', sa.String(), sa.ForeignKey('users.uid'), nullable=True),
        sa.Column('change_type', sa.String(length=50), nullable=False),
        sa.Column('quantity_changed', sa.Float(), nullable=False),
        sa.Column('previous_quantity', sa.Float(), nullable=False),
        sa.Column('new_quantity', sa.Float(), nullable=False),
        sa.Column('reason', sa.String(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_update_logs')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
