"""add_uid_role_table_to_orders

Revision ID: 53611d32e43f
Revises: order_id_format_change
Create Date: 2025-05-16 09:05:21.785849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53611d32e43f'
down_revision = 'order_id_format_change'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='user_uid', existing_type=sa.String(), nullable=False)
        batch_op.add_column(sa.Column('user_role', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('table_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('table_number')
        batch_op.drop_column('user_role')
        batch_op.alter_column('user_uid', new_column_name='user_id', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###
