"""add_customer_uid_to_orders

Revision ID: 61fbc8887b89
Revises: 6e21c8766b52
Create Date: 2025-05-17 12:21:51.736961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fbc8887b89'
down_revision = '6e21c8766b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_uid', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_customer_uid'), ['customer_uid'], unique=False)
        batch_op.create_foreign_key(
            batch_op.f('fk_orders_customer_uid_users'),
            'users', # Referent table
            ['customer_uid'], # Local columns
            ['uid'], # Remote columns
            ondelete='SET NULL'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        # batch_op.drop_constraint(batch_op.f('fk_orders_customer_uid_users'), type_='foreignkey') # Constraint might not exist
        batch_op.drop_index(batch_op.f('ix_orders_customer_uid'), if_exists=True) # Attempt to make index drop more robust
        batch_op.drop_column('customer_uid')
    # ### end Alembic commands ###
