"""add_combo_menu_items

Revision ID: 6e21c8766b52
Revises: f7b5695c43b9
Create Date: 2025-05-17 12:15:10.729838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e21c8766b52'
down_revision = 'f7b5695c43b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('item_type', sa.String(length=50), server_default='REGULAR', nullable=False))
    op.create_index(op.f('ix_menu_items_item_type'), 'menu_items', ['item_type'], unique=False)

    op.create_table('combo_item_components',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('combo_menu_item_id', sa.Integer(), nullable=False),
        sa.Column('component_menu_item_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False, server_default="1"),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), onupdate=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(['combo_menu_item_id'], ['menu_items.id'], name=op.f('fk_combo_item_components_combo_menu_item_id_menu_items'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['component_menu_item_id'], ['menu_items.id'], name=op.f('fk_combo_item_components_component_menu_item_id_menu_items'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_combo_item_components')),
        sa.UniqueConstraint('combo_menu_item_id', 'component_menu_item_id', name=op.f('uq_combo_item_components_combo_menu_item_id'))
    )
    op.create_index(op.f('ix_combo_item_components_combo_menu_item_id'), 'combo_item_components', ['combo_menu_item_id'], unique=False)
    op.create_index(op.f('ix_combo_item_components_component_menu_item_id'), 'combo_item_components', ['component_menu_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combo_item_components_component_menu_item_id'), table_name='combo_item_components')
    op.drop_index(op.f('ix_combo_item_components_combo_menu_item_id'), table_name='combo_item_components')
    op.drop_table('combo_item_components')
    
    op.drop_index(op.f('ix_menu_items_item_type'), table_name='menu_items')
    op.drop_column('menu_items', 'item_type')
    # ### end Alembic commands ###
