"""add_fields_to_menu_items

Revision ID: 7fec563f0c02
Revises: 5e9c6948cf81
Create Date: 2025-05-16 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fec563f0c02'
down_revision = '5e9c6948cf81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('menu_items', sa.Column('variations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'variations')
    op.drop_column('menu_items', 'cost_price')
    # ### end Alembic commands ###
