"""init tables

Revision ID: bb8c1ff5c2eb
Revises: 
Create Date: 2025-04-18 22:19:05.360252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8c1ff5c2eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_table('restaurants',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_name', sa.String(), nullable=True),
    sa.Column('offers', sa.JSON(), nullable=True),
    sa.Column('points_per_rupee', sa.Float(), nullable=True),
    sa.Column('reward_thresholds', sa.JSON(), nullable=True),
    sa.Column('referral_rewards', sa.JSON(), nullable=True),
    sa.Column('owner_uid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurants_restaurant_id'), 'restaurants', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurants_restaurant_name'), 'restaurants', ['restaurant_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_restaurants_restaurant_name'), table_name='restaurants')
    op.drop_index(op.f('ix_restaurants_restaurant_id'), table_name='restaurants')
    op.drop_table('restaurants')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
