"""\replace_promocodes_with_coupons_and_usage\

Revision ID: c44d3bcb0e90
Revises: 59a0b9621bf7
Create Date: 2025-05-16 17:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44d3bcb0e90'
down_revision = '59a0b9621bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the old promo_codes table
    # First, need to drop FK in 'orders' table if it exists and points to promo_codes.id
    # Inspecting the Order model, promo_code_id was Column(Integer, ForeignKey("promo_codes.id"))
    # However, direct FK dropping in SQLite is tricky. Batch mode handles table recreation.
    # For simplicity and given this is a replacement, we'll ensure Order.promo_code_id is handled.
    # The Order model was already updated to remove promo_code_id. 
    # If a migration for that change hasn't run or was part of a larger one, 
    # this drop_table might fail if an FK still exists from orders to promo_codes.
    # Assuming previous model changes have removed direct FK from Order table definition.
    op.drop_table('promo_codes')

    # Create new 'coupons' table
    op.create_table('coupons',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('code', sa.String(length=50), nullable=False, unique=True, index=True),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('coupon_type', sa.String(length=50), nullable=False),
        sa.Column('discount_value', sa.Float(), nullable=True),
        sa.Column('discount_percentage', sa.Float(), nullable=True),
        sa.Column('menu_item_id', sa.Integer(), sa.ForeignKey('menu_items.id'), nullable=True),
        sa.Column('menu_category_id', sa.Integer(), sa.ForeignKey('menu_categories.id'), nullable=True),
        sa.Column('category_offer_type', sa.String(length=50), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('usage_limit', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('per_user_limit', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('assigned_user_ids', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False), # Ensuring not nullable with server_default
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('restaurant_id', sa.String(), sa.ForeignKey('restaurants.restaurant_id'), nullable=True, index=True),
        sa.Column('parent_coupon_id', sa.Integer(), sa.ForeignKey('coupons.id'), nullable=True, index=True)
    )

    # Create new 'coupon_usages' table
    op.create_table('coupon_usages',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('coupon_id', sa.Integer(), sa.ForeignKey('coupons.id'), nullable=False, index=True),
        sa.Column('user_uid', sa.String(), sa.ForeignKey('users.uid'), nullable=False, index=True),
        sa.Column('order_id', sa.String(), sa.ForeignKey('orders.id'), nullable=True, index=True),
        sa.Column('used_at', sa.DateTime(), server_default=sa.func.now(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_usages')
    op.drop_table('coupons')

    # Recreate 'promo_codes' table (simplified version from original model)
    op.create_table('promo_codes',
        sa.Column('id', sa.Integer(), nullable=False, primary_key=True, index=True),
        sa.Column('code', sa.String(), nullable=True, unique=True, index=True),
        sa.Column('discount_percent', sa.Float(), nullable=True),
        sa.Column('discount_amount', sa.Float(), nullable=True),
        sa.Column('valid_from', sa.DateTime(), nullable=True),
        sa.Column('valid_to', sa.DateTime(), nullable=True),
        sa.Column('usage_limit', sa.Integer(), nullable=True),
        sa.Column('used_count', sa.Integer(), server_default='0', nullable=True),
        sa.Column('restaurant_id', sa.String(), sa.ForeignKey('restaurants.restaurant_id'), nullable=True),
        sa.Column('active', sa.Boolean(), server_default=sa.true(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True)
    )
    # Note: Downgrade does not restore FK from orders.promo_code_id as that column should be gone.
    # ### end Alembic commands ###
