"""Add restaurant_id to MenuCategory

Revision ID: e4c3ec824012
Revises: 2e38b4c5d7c0
Create Date: 2025-04-28 11:51:42.372522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c3ec824012'
down_revision = '2e38b4c5d7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('menu_categories', sa.Column('restaurant_id', sa.String(), nullable=True))  # Already exists, skip adding
    # op.create_index(op.f('ix_menu_categories_restaurant_id'), 'menu_categories', ['restaurant_id'], unique=False)  # Already exists, skip
    # op.create_foreign_key(None, 'menu_categories', 'restaurants', ['restaurant_id'], ['restaurant_id'])  # Already exists, skip
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    op.drop_index(op.f('ix_menu_categories_restaurant_id'), table_name='menu_categories')
    op.drop_column('menu_categories', 'restaurant_id')
    # ### end Alembic commands ###
